### ISSUE TITLE
xdelta tries to read too much data

### ISSUE THREAD

**Issue by arthur-proglove** [fwup-home/fwup#198]
In `fwup_apply.c`:

https://github.com/fwup-home/fwup/blob/c9918f7aa730d07a26a468ba1b1506fb6740b931/src/fwup_apply.c#L250

When xdelta tries to read a new block of 128KiB out of bound, shouldn't `count` be set to `fctx->xd_source_count - offset` instead of throwing an error? That way xdelta can reads at most `xd_source_count`?

**Comment by fhunleth** [comment]
Interesting. I feel like I agree with you, but I'm unsure as to how I have used xdelta so much without running into this. Are you able to make this happen? I'd really like to see if I can make a unit test out of it.

**Comment by arthur-proglove** [comment]
Alright, sorry for not mentioning the context how I ran into this :-).

I have a system with 2 A/B partitions of 2.5GiB each. 
But my root filesystem is not occupying the 2.5GiB, it's occupying only around 700MiB. 

So, when modifying the firmware update to include the delta rootfs (https://github.com/fwup-home/fwup#delta-firmware-updates-beta) I also modified the meta.conf.
Instead of setting `delta-source-raw-count=5242880` (2.5GiB) I set it to the size of the root file system.
For instance, if my root filesystem size is `749879296` bytes I set `delta-source-raw-count` to `1464608`.
My idea behind is that `xdelta` would only check the actual occupied bytes on the device and would not care about the 1.8 unused GiB. And this method fails because xdelta wants to read 128KiB when is less to be read for the last read call.

But maybe there is no need to think that way? What does fwup/xdelta expect for the unused space?

**Comment by fhunleth** [comment]
Ahh. That makes sense. I always set the `delta-source-raw-count` to the whole partition. I agree that `xdelta` shouldn't care about the 1.8 unused GiB in your case. I've never thought of using `delta-source-raw-count` to be more restrictive with `xdelta`, though. Since `fwup` also verifies a checksum on `xdelta`'s output, I feel that if `xdelta` goes haywire and reads into that 1.8 GiB, that it will be detected on the output. It doesn't seem like there should be any sensitive data in that 1.8 GiB either since it's been allocated to the rootfs and you'd keep secrets in another place.

If I were you, I'd set the `delta-source-raw-count` to the full partition and not worry about being more restrictive. However, I also feel like you bring up a good point on how `fwup` is handling out of bound reads by `xdelta` and maybe it should just return what it can rather than give an error. If you are ok with this, I'm tempted to leave this issue open so that I'll see it on my next `fwup` maintenance pass and make the change then. Feel free to send a PR if you want it sooner.

**Comment by arthur-proglove** [comment]
Yeah I guess reading the whole partition is not that bad but I can definitely try to create a PR to only read the available space.

Also, I'm trying this on a Raspberry Pi 0 W and the delta update is awfully slow :-(

**Comment by fhunleth** [comment]
> Also, I'm trying this on a Raspberry Pi 0 W and the delta update is awfully slow :-(

That's been my experience on some processors as well. I really only use delta updates when updating devices over metered connections. I suspect that the Pi Zero's relatively slow MicroSD card performance doesn't help either.
